[config]
schemaVersion = "0.0.1"

[package]
namespace = "MioMods"
name = "I18nCN"
versionNumber = "1.2.9"
description = "Translate the mod, translate all mods into Chinese "
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
CaptainOfCoit-HookUI = "0.3.5"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./ts-build"

[publish]
repository = "https://thunderstore.io"
communities = [ "cities-skylines-ii", ]
categories = [ "mods" ]
